# ansible_user: "{{ terraform_user }}"
# ansible_password: "{{ terraform_pwd }}"
#ansible_port: 22
#ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
#ansible_ssh_retries: 3
#ansible_shell_type: powershell
#ansible_become_method: runas
# ansible_become_user: "{{ ansible_user }}"
# ansible_become: true
#ansible_become_user: "administrator@test.lab"
#ansible_become_password: "{{ administrator_password }}"
