- name: Set timezone to 'W. Europe Standard Time'
  win_timezone:
    timezone: "{{ vm_timezone }}"

- name: Disable IE ESC for Admins
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}
    name: IsInstalled
    data: 0
    type: dword

- name: Disable IE ESC for Users
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}
    name: IsInstalled
    data: 0
    type: dword

- name: Disable ServerManager for all Users
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\ServerManager
    name: DoNotOpenServerManagerAtLogon
    data: 1
    type: dword

- name: Disable ServerManager for current user
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\ServerManager
    name: CheckedUnattendLaunchSetting
    data: 0
    type: dword

- name: Disable First run wizard on MS Edge
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Edge
    name: HideFirstRunExperience
    data: 1
    type: dword

- name: Install telnet client
  ansible.windows.win_feature:
    name: telnet-client
    state: present

- name: Disable Windows firewall
  community.windows.win_firewall:
    state: disabled
  tags: disable_firewall

- name: Install Required Software from chocolatey
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: 
    - notepadplusplus
    - powershell-core

