- name: Set current host variable
  set_fact:
    current_host: "{{ inventory_hostname | replace('ansible_host=','')}}"

- name: Change administrator
  ansible.builtin.shell: python3 /var/requirements/change_ns_password.py http://localhost:4444/wd/hub https://{{ current_host }} {{ instance_id }} {{ administrator_password }}
  delegate_to: "{{ item }}"
  loop: "{{ groups['monitoring'] }}"

- name: Create SNIP
  ansible.builtin.uri:
    url: https://{{ current_host }}/nitro/v1/config/nsip?idempotent=yes
    validate_certs: no
    method: POST
    status_code: [200, 201]
    body_format: json
    headers:
      X-NITRO-User: nsroot
      X-NITRO-PASS: "!Friskies2019!"
      Content-Type: application/json
    body:
      nsip: {
        "ipaddress":"192.168.3.8",
        "netmask": "255.255.255.0",
        "type": "SNIP"
      }
  register: prova
  delegate_to: "{{ item }}"
  loop: "{{ groups['monitoring'] }}"