- name: Create SNIP
  ansible.builtin.uri:
    url: https://34.90.64.16/nitro/v1/config/nsip?idempotent=yes
    validate_certs: no
    method: POST
    status_code: [200, 201]
    body_format: json
    headers:
      X-NITRO-User: nsroot
      X-NITRO-PASS: "!Friskies2019!"
      Content-Type: application/json
    body:
      nsip: {
        "ipaddress":"192.168.3.8",
        "netmask": "255.255.255.0",
        "type": "SNIP"
      }
  register: prova
  delegate_to: "{{ item }}"
  loop: "{{ groups['monitoring'] }}"

- name: Show get_current_storefrontconfig Hypervisors
  ansible.builtin.debug:
    var: prova

# - name: Add HA Node
#   ansible.builtin.uri:
#     url: https://34.90.64.16/nitro/v1/config/hanode?idempotent=yes
#     validate_certs: no
#     method: POST
#     status_code: [200, 201, 409]
#     body_format: json
#     headers:
#       X-NITRO-User: nsroot
#       X-NITRO-PASS: "!Friskies2019!"
#       Content-Type: application/json
#     body:
#       hanode: {
#         "id":"1",
#         "ipaddress": "192.168.3.7",
#         "inc": "ENABLED"
#       }
#   register: hanode

# - name: Show get_current_storefrontconfig Hypervisors
#   ansible.builtin.debug:
#     var: hanode

- name: Create a directory if it does not exist
  ansible.builtin.copy:
    src: "./CNS_V100000_SERVER_PLT_Retail.lic"
    dest: /flash/nsconfig/license/CNS_V100000_SERVER_PLT_Retail.lic
    mode: '0777'
