- name: Create Bearer token
  ansible.builtin.uri:
    url: https://api.cloud.com/cctrustoauth2/root/tokens/clients
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: "client_credentials"
      client_id: "{{ citrix_client_id }}"
      client_secret: "{{ citrix_client_secret }}"
  register: token

# Enumerate Resource location and check if already exists
- name: Get current Resource Location
  ansible.builtin.uri:
    url: "https://registry.citrixworkspacesapi.net/{{ citrix_tenant }}/resourcelocations"
    method: GET
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
  register: current_resloc

- name: Define NetBios domain name
  ansible.windows.win_powershell:
    script: |
      $netbios_ad=Get-WmiObject Win32_NTDomain -Filter "DnsForestName = '$( (Get-WmiObject Win32_ComputerSystem).Domain)'"
      $netbios_ad.DomainName
  register: pws_output
  delegate_to: "{{ item }}"
  loop: "{{ groups['domaincontroller'] }}"

- name: Set netbios_name variable
  ansible.builtin.set_fact:  
    netbios_name: "{{ pws_output.results[0].output[0] }}"

# Iterate current_resloc variable searching for resource_location_name
- name: Search for already existing resource location with the same name
  set_fact:
    resloc_search: "{{ current_resloc | community.general.json_query(query) | join(', ') }}"
  vars:
    query: "json.items[?name=='{{ resource_location_name }}'].name"

- name: If resource location already exists, taking the ID in resloc_id variable
  set_fact:
    resloc_id: "{{ current_resloc | community.general.json_query(query) | join(', ') }}"
  vars:
    query: "json.items[?name=='{{ resource_location_name }}'].id"
  when: resloc_search

- name: Create Resource Location if not exists
  ansible.builtin.uri:
    url: "https://registry.citrixworkspacesapi.net/{{ citrix_tenant }}/resourcelocations"
    method: POST
    body_format: json
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
    body:
      Name: "{{ resource_location_name }}"
      internalOnly: "false"
      readOnly: "false"
  when: resloc_search != resource_location_name
  register: resloc

- name: Set resloc_id variable with resource location id 
  set_fact:
    resloc_id: "{{ resloc.json.id }}"
  when: resloc_search != resource_location_name

- name: Get SiteID
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/me"
    method: GET
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
  register: get_citrix_siteid

- name: Set citrix_siteid var
  set_fact:
    citrix_siteid: "{{ get_citrix_siteid.json.Customers[0].Sites[0].Id }}"


## Setting Hosting Connection

- name: Get Existing hosting connections
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/hypervisors"
    method: GET
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
  register: get_citrix_hypervisors


- name: Search for already existing hosting connector with the same name
  set_fact:
    resloc_search: "{{ get_citrix_hypervisors | community.general.json_query(query) | join(', ') }}"
  vars:
    query: "json.Items[?Name=='{{ hosting_connection_name }}'].Name"

- name: Sleep for 120 to be sure all services are running
  ansible.builtin.wait_for:
    timeout: 10
  delegate_to: localhost


- name: Create Hosting Connection
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/hypervisors"
    method: POST
    body_format: json
    status_code: [200, 201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
    body:
      ConnectionDetails: 
        Name: "{{ hosting_connection_name }}"
        ConnectionType: "GoogleCloudPlatform"
        ServiceAccountId: "{{ gcp_sa_name }}"
        Zone: "{{ resource_location_name }}"
        ServiceAccountCredentials: "{{ gcp_sa_privatekey }}"
      PoolDetails:
        ConnectionType: "GoogleCloudPlatform"
        Name: "{{ hosting_connection_resoucepool_name }}"
        Region: "XDHyp:\\Connections\\{{ hosting_connection_name }}\\{{ gcp_project_name }}.project\\{{ gcp_region }}.region"
        VirtualPrivateCloud: "XDHyp:\\Connections\\{{ hosting_connection_name }}\\{{ gcp_project_name }}.project\\{{ gcp_region }}.region\\{{ vpcname }}.virtualprivatecloud"
        Networks: ["XDHyp:\\Connections\\{{ hosting_connection_name }}\\{{ gcp_project_name }}.project\\{{ gcp_region }}.region\\{{ vpcname }}.virtualprivatecloud\\{{ subnetname }}.network"]
  when: resloc_search != hosting_connection_name
  register: create_hostingconnection

- name: Validate Credential for join MCS VMs
  ansible.builtin.uri:
    url: "https://{{ citrix_tenant }}.xendesktop.net/citrix/orchestration/api/techpreview/{{ citrix_tenant }}/{{ citrix_siteid }}/Identity/Users/$validate"
    method: POST
    body_format: json
    status_code: [200, 201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
    body:
      UserName: "Administrator"
      Domain: "{{ domain_name }}"
      Password: "{{ administrator_password }}"
  register: validatecred

- name: Create correct credential variable
  set_fact:
    cred: "{{ validatecred.json.DisplayName }}:{{ administrator_password }}"


- name: Encode Administrator Password
  ansible.builtin.shell: echo "{{ cred | string | b64encode }}"
  register: encodedpass

- name: Get current Machine Catalogs
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/MachineCatalogs"
    method: GET
    body_format: json
    status_code: [200, 201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
      X-AdminCredential: "Basic {{ encodedpass.stdout }}"
  register: current_machinecatalogs

- name: Search if Machine Catalog with the same name already exists
  ansible.builtin.set_fact:
    search_machinecatalog: "{{ current_machinecatalogs | community.general.json_query(query) | join(', ') }}"
  vars:
    query: "json.Items[?Name=='{{ machinecatalog_name }}'].Name"

- name: Use existing ID if machine catalog already exists
  ansible.builtin.set_fact:
    search_machinecatalog_id: "{{ current_machinecatalogs | community.general.json_query(query) | join(', ') }}"
  vars:
    query: "json.Items[?Name=='{{ machinecatalog_name }}'].Id"
  when: search_machinecatalog == machinecatalog_name


- name: Get current machine catalog
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/MachineCatalogs/{{ search_machinecatalog_id }}"
    method: GET
    body_format: json
    status_code: [200, 201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
  register: machinecatalog_already_exists
  when: search_machinecatalog == machinecatalog_name

- name: Create Machine Catalog if not exists
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/MachineCatalogs"
    method: POST
    body_format: json
    status_code: [200, 201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
      X-AdminCredential: "Basic {{ encodedpass.stdout }}"
    body:
      Name: "{{ machinecatalog_name }}"
      AllocationType: "Random"
      MinimumFunctionalLevel: "L7_25"
      PersistUserChanges: "Discard"
      ProvisioningType: "MCS"
      SessionSupport: "MultiSession"
      Zone: "{{ resource_location_name }}"
      ProvisioningScheme:
        MasterImagePath: "XDHyp:\\HostingUnits\\{{ hosting_connection_resoucepool_name }}\\{{ masterimagename }}.vm"
        CpuCount: 2
        MemoryMB: 8192
        NumTotalMachines: "{{ vm2deply }}"
        NetworkMaps: [
          "NetworkPath":"XDHyp:\\HostingUnits\\{{ hosting_connection_resoucepool_name }}\\{{ subnetname }}.network"]
        MachineAccountCreationRules:
          NamingScheme: "MCS-VDA##"
          NamingSchemeType: "Numeric"
          Domain: "{{ domain_name }}"
          OU: ""
        PrepareImage: true
        DedicatedTenancy: false
        SecurityGroups: null
        UseFullDiskCloneProvisioning: false
        CustomProperties: [{
            "Name":"CatalogZones",
            "Value": "{{ gcp_project_id }}:{{ gcp_region }}:a" },
            {"Name": "StorageType",
              "Value": "pd-standard" }
          ]
  register: machinecatalog
  when: search_machinecatalog != machinecatalog_name

- name: Restore machinecatalog variable 
  ansible.builtin.set_fact:
    machinecatalog : "{{ machinecatalog_already_exists }}"
  when: search_machinecatalog == machinecatalog_name

- name: Get current Machine Catalogs preparation
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/MachineCatalogs/{{ machinecatalog.json.Id }}"
    method: GET
    body_format: json
    status_code: [200, 201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
      X-AdminCredential: "Basic {{ encodedpass.stdout }}"
  register: check_machinecatalogs
  until: check_machinecatalogs.json.ProvisioningProgress == None
  retries: 50
  delay: 60
  when: search_machinecatalog != machinecatalog_name

- name: Create Delivery Group
  ansible.builtin.uri:
    url: "https://api.cloud.com/cvad/manage/DeliveryGroups?detailResponseRequired=true&async=false"
    method: POST
    body_format: json
    status_code: [200,201]
    headers:
      Authorization: "CwsAuth bearer={{ token.json.access_token }}"
      Citrix-CustomerId: "{{ citrix_tenant }}"
      Citrix-InstanceId: "{{ citrix_siteid }}"
    body:
      Name: "{{ deliverygroup_name }}"
      MachineCatalogs: [{
        "MachineCatalog":"{{ machinecatalog.json.Id }}",
        "Count": "{{ vm2deply }}",
        "AssignMachinesToUsers": [] }
        ]
      DeliveryType: "DesktopsAndApps"
      Desktops: [{
        "Enabled": "true",
        "IncludedUserFilterEnabled": "false",
        "IncludedUsers":[],
        "PublishedName":"Ubuntu Lab Desktop",
        "MaxDesktops":1 }
        ]
      MinimumFunctionalLevel: "L7_25"
      AutoScaleEnabled: false
      RequireUserHomeZone: false
      SimpleAccessPolicy:
        IncludedUsers: ["{{ netbios_name }}\\{{ adgroup2create }}"]
        AllowAnonymous: false
        IncludedUserFilterEnabled: true
      UserManagement: "Studio"
  register: create_deliverygroup

